### ISSUE TITLE
iOS source code?

### ISSUE THREAD

**Issue by sg-s** [enriquez/coinpocketapp.com#37]
Hi,

Congratulations on getting your app on the iOS store! took a long time and people are going nuts over it. do you have any plans to show us the source of the iOS app, and is there any way to verify code integrity of the app on our phone? 

S

**Comment by koumolo** [comment]
Dear Enriquez,
Is the app still accesable? Why is it shut down?

**Comment by enriquez** [comment]
@koumolo CoinPocket is no longer available to download.  The project was no longer maintained and was allowed to expire.

If you still have CoinPocket, I recommend getting your encrypted private key out and moving to a different wallet.

**Comment by koumolo** [comment]
Thanks for the reaction,
I’m not able to download the app. Is there an other way to retreive my private key? 

Met vriendelijke groet,
Arthur Mol

**Comment by enriquez** [comment]
@koumolo No, sorry your private key would've been deleted along with the app.

Your best bet is to try to find a backup if you made one.

**Comment by koumolo** [comment]
I hope so. Thanks 

Met vriendelijke groet,
Arthur Mol
